name=ezTime2
version=1.0.0
author=Dag0d
maintainer=Dag0d
sentence=ezTime2 - pronounced "Easy Time" - is an Arduino time and date library with NTP sync, timezone lookups, formatted output, events, and millisecond precision.
paragraph=See more on https://github.com/Dag0d/ezTime2
category=Timing
url=https://github.com/Dag0d/ezTime2
architectures=*
includes=ezTime2.h
